from models.potential_outcomes.cfrnet import CFR

class TARNet(CFR):
    def __init__(self, network_name,
                 input_dim, hidden_sizes_phi, hidden_sizes_y, phi_dim,
                 outcome_dist, num_treatments,
                 experiment, model_path,
                 device,
                 weight_init_phi=None, weight_init_y=None, dropout=0.0, activation='relu',
                 min_std=None, max_std=None, min_shape=None, max_shape=None, min_scale=None, max_scale=None,
                 fixed_std=None,
                 limit_variance=False, fix_variance=False, limit_shape=False, limit_scale=False,
                 kan_params_y=None, kan_params_phi=None,
                 min_outcome=None,
                 save=True, optim_config=None, wandblog=False, is_subnetwork=False):
        divergence_loss = None
        beta_div=0
        super(TARNet, self).__init__(network_name = network_name,
                                     input_dim = input_dim,
                                     hidden_sizes_phi = hidden_sizes_phi,
                                     hidden_sizes_y = hidden_sizes_y,
                                     phi_dim = phi_dim,
                                     outcome_dist = outcome_dist,
                                     num_treatments = num_treatments,
                                     divergence_loss =divergence_loss,
                                     beta_div = beta_div,
                                     experiment = experiment,
                                     model_path = model_path,
                                     dropout = dropout,
                                     activation = activation,
                                     device = device,
                                     weight_init_phi = weight_init_phi,
                                     weight_init_y = weight_init_y,
                                     min_std=min_std,
                                     max_std=max_std,
                                     min_shape=min_shape,
                                     max_shape=max_shape,
                                     min_scale=min_scale,
                                     max_scale=max_scale,
                                     fixed_std=fixed_std,
                                     limit_variance=limit_variance,
                                     fix_variance=fix_variance,
                                     limit_shape=limit_shape,
                                     limit_scale=limit_scale,
                                     min_outcome=min_outcome,
                                     save = save,
                                     optim_config = optim_config,
                                     wandblog = wandblog,
                                     is_subnetwork = is_subnetwork,
                                     kan_params_y = kan_params_y,
                                     kan_params_phi = kan_params_phi)
